name: Build

on:
  push:
    branches:
      - feature/**
      
env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install mocha
        run: npm install -g mocha

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test